// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF-GDrEHHWi9JXEE_S5aZp3EmSXFvc4eQ',
    appId: '1:276269009592:web:04226708a786b5c87e024d',
    messagingSenderId: '276269009592',
    projectId: 'diciannove-c1c4f',
    authDomain: 'diciannove-c1c4f.firebaseapp.com',
    storageBucket: 'diciannove-c1c4f.appspot.com',
    measurementId: 'G-T61WJ7H11E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaTzL9YmWIA8GmXSUedbxfejw4kKvt7VY',
    appId: '1:276269009592:android:1351388215ba05bd7e024d',
    messagingSenderId: '276269009592',
    projectId: 'diciannove-c1c4f',
    storageBucket: 'diciannove-c1c4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYCnekjym1JOUpwyh3HfSXOLxPfhyyHQ8',
    appId: '1:276269009592:ios:b67ff67cc2d27e657e024d',
    messagingSenderId: '276269009592',
    projectId: 'diciannove-c1c4f',
    storageBucket: 'diciannove-c1c4f.appspot.com',
    iosClientId: '276269009592-6cmk8i9vm7jqu60r6qkfcta4354b717i.apps.googleusercontent.com',
    iosBundleId: 'com.example.talento',
  );

}